#开发环境配置
server:
  port: 8099
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
spring:
  application:
    name: background-manager
# redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1800000
  data:
  #spring cloud 配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#mysql配置
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.134.15:3306/background_manager?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: Menghu@nbicc2023
        salve:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.134.15:3306/background_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: Menghu@nbicc2023
#文件上传配置
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#FTP相关配置
FTP:
  address: 127.0.0.1
  port: 22
  username: pwftp
  password: pwftp
  basePath: /mnt/sdc/ftpuser/images/
#图片服务器相关配置
IMAGE:
  BASE:
    URL: https://img.nbaicc.com
security:
  excludes:
    # 静态资源
    - /**/*.css
    - /**/*.js
    - /doc.html/**
    - /swagger-resources/**
    - /webjars/**
    - /*/api-docs/**
    - /error
    # druid 监控配置
    - /druid/**
    # 登录注册
    - /register
    - /login
    #开放的新闻模块
    - /activity/**
    - /carousel/**
    - /column/**
    - /article/**
    - /offline/**
    - /resource/**
    - /home/**
    - /style/listQuery
    - /style/listInfrastructure
    - /seo/listQuery
    - /checkLogin
#Swagger配置
swagger:
  #正式环境禁用swagger
  enabled: false
  title: "超算中心后台运营管理—接口文档"
  description: "超算中心后台运营管理"
  version: "V1.0"
#Sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 36000
  # token临时有效期,单位s 默认15分钟，15分钟不操作token过期
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # sk-token前缀
  token-prefix: Bearer
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否从cookie里读取token  is-read-cookie: true
  #是否从请求体里读取token
  is-read-body: false
# 配置线程池
thread:
  # 线程核心数
  corePoolSize: 5
  # 线程最大数
  maxPoolSize: 8
  # 任务容量
  queueCapacity: 15
  # 允许空闲时间
  keepAlive: 120
# 超算智算第三方接口配置
sm2:
  server:
    cs:
      privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgN0L9YT41CwTEQhAL6QYDe+IyHFxiZdrAQDCmCo4FwK+gCgYIKoEcz1UBgi2hRANCAATQ0b9ruVKjcZz8OSulhybqCgf2Mcdg+4piZIOuEhQFB1LDX1De+luMr+xgzqWbfq/EZLE7OOvYIiE4iBC6wBlk
    zs:
      privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQg7zSTlfFboMa8BjmDxVK1R2/X1yBGUPEZjq5C2t/M2K6gCgYIKoEcz1UBgi2hRANCAAQsm587086khNwzJOcS++XX1MBTFgtsYasF0h6oF1So49dMQz5BeKyGG07/q0yE7yxqXf32xwcD8pbtG9bgc+ks
  cs:
    publicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEM/qZv8rpwhFHDXxQj25Pvzj2HYFhvJSNITqBnRq+BHpHifyZdy2S6moqo9MHq2VYs0v06bxp4vEFtgxlWuD3KA==
  zs:
    publicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEi+7Ngv93BoQs8e0I9fit9NpJoK4vJeHLBz0tHh8hj/jSKoXgA1UPYrsTFx6Ws/PDfFndbZ0A11VD+iaIZDQeYg==
#超算智算url地址
zs:
  console:
    url: https://uconsole.nbaicc.com
  manage:
    url: https://mgt.nbaicc.com
    userId: 100
cs:
  console:
    url: https://172.17.134.102:443
  manage:
    userId: 100

